### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(CheckPaymentFormContent)
add_subdirectory(CheckPaymentForm)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    CheckPaymentFormContentplugin
    CheckPaymentFormplugin)